volumes:
  ecotrack_postgres_data:

services:
  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432" # Port standard pour PostgreSQL
    volumes:
      - ecotrack_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecotrack
