name: .Net CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Restore dependencies
        run: dotnet restore Backend/EcoTrack.Authentification/EcoTrack.Authentification.sln

      - name: Build solution
        run: dotnet build Backend/EcoTrack.Authentification/EcoTrack.Authentification.sln --no-restore --configuration Release
      
      - name: Run tests
        run: dotnet test Backend/EcoTrack.Authentification/EcoTrack.Authentification.sln --no-build --configuration Release --verbosity normal
