name: .Net CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Restore, Build, and Test
        run: |
          cd Backend/EcoTrack.Authentification
          dotnet restore
          dotnet build --no-restore --configuration Release
          dotnet test --no-build --configuration Release --verbosity normal
